version: '2.1'

services:
  rocketmq-base:
    image: rocketmq-base-image:4.0.0-incubating
    build: ./base

  rocketmq-namesrv:
    image: rocketmq-namesrv-image:4.0.0-incubating
    build:
      context: ./namesrv
      args:
        BASE_IMAGE: rocketmq-base-image:4.0.0-incubating
    ports:
      - "9876:9876"
    depends_on:
      - rocketmq-base

  rocketmq-broker-a-m:
    image: rocketmq-broker-a-m-image:4.0.0-incubating
    build:
      context: ./broker
      args:
        BASE_IMAGE: rocketmq-base-image:4.0.0-incubating
        BROKER_IP1: localhost
        LISTEN_PORT: 10911
        PROPERTIES_FILE: "2m-2s-async/broker-a.properties"
    environment:
      NAMESRV_ADDR: "rocketmq-namesrv:9876"
      BROKER_IP1: "rocketmq-broker-a-m"
      BROKER_ADDR: "rocketmq-broker-a-m"
    ports:
      - "10911:10911"
      - "10909:10909"
    depends_on:
      - rocketmq-base
      - rocketmq-namesrv
    links:
      - rocketmq-namesrv

  pub-service:
    image: pub-service:latest
    build:
      context: ./pub-service
    environment:
      NAMESRV_ADDR: "rocketmq-namesrv:9876"
      BROKER_IP1: "rocketmq-broker-a-m"
      BROKER_ADDR: "rocketmq-broker-a-m"
    ports:
      - "9909:9909"
    depends_on:
      - rocketmq-base
      - rocketmq-namesrv
    links:
      - rocketmq-namesrv
      - rocketmq-broker-a-m

  # rocketmq-console:
  #   image: rocketmq-console:latest
  #   build:
  #     context: ./rocketmq-console
  #   environment:
  #     NAMESRV_ADDR: rocketmq-namesrv:9876
  #     BROKER_IP1: "rocketmq-broker-a-m"
  #     # - "rocketmq.config.namesrvAddr=rocketmq-namesrv"
  #     # rocketmq.config.brokerIP1: rocketmq-broker-a-m"
  #   links:
  #     - rocketmq-namesrv
  #     - rocketmq-broker-a-m
  #   ports:
  #     - 8080:8080